/*
 * task_manager.h
 *
 *  Created on: Apr 24, 2023
 *      Author: Boris Ivanov
 *
 *  Description: Receives tasks generated by C-M7. Based on the task given, the states of C-M4 will change accordingly,
 *  together with any necessary data changes.
 *
 */

#ifndef INC_LEVEL_2_TASK_MANAGER_H_
#define INC_LEVEL_2_TASK_MANAGER_H_



#endif /* INC_LEVEL_2_TASK_MANAGER_H_ */
