/*
 * task_manager.h
 *
 *  Created on: Apr 24, 2023
 *      Author: Boris Ivanov
 *
 *  Description: Receives tasks generated by C-M7. Based on the task given, the states of C-M4 will change accordingly,
 *  together with any necessary data changes.
 *
 */

#ifndef INC_LEVEL_2_TASK_MANAGER_H_
#define INC_LEVEL_2_TASK_MANAGER_H_

#include "main.h"
#include "vars.h"
#include <string.h>
#include "level_3/servo_controller.h"
#include "peripheral_devices/usart.h"
#include "D:\University\Fontys\Year5\Internship\STM32H_Example Codes\CURRENT\Dual_Core__High_Level_Arch_STABLE\Dual_Core__High_Level_Arch_STABLE\Dual_Core__High_Level_Arch\Common\Inc\common.h"

/* VARIABLES */

/* FUNCTIONS */
void activate_HSEM_Notifications(void);
void gameplay_loop_CM4(int state);
void state_init();
void state_idle();
void state_robot_move();
void state_human_move();
void state_clean_up();
void state_cheat_detected();
void state_game_end();

#endif /* INC_LEVEL_2_TASK_MANAGER_H_ */
